### ISSUE TITLE
别人发的issue会触发github action吗

### ISSUE THREAD

**Issue by tokisakiyuu** [Shell32-Natsu/Shell32-Natsu.github.io#17]
我在搭建类似的系统

**Comment by tokisakiyuu** [comment]
发评论会触发吗

**Comment by tokisakiyuu** [comment]
> 发评论会触发吗

不会

**Comment by tokisakiyuu** [comment]
打扰了，哈哈哈哈，谢谢🙏

**Comment by Shell32-Natsu** [comment]
在GitHub Action的实现里面可以检查创建issue的user ID。

**Comment by tokisakiyuu** [comment]
> 在GitHub Action的实现里面可以检查创建issue的user ID。

您的意思是在Action Context里面去拿事件的详细信息吧，那么还是先得把workflow执行起来，会生成一条workflow记录，除此之外，如果是恶意高频发issue，有没有可能会触发Github Action的某种[限制](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#usage-limits)呢？

我现在打算用一个Milestone来标记文章，一个Milestone是一层天然的issue namespace，而不用label去模拟，这点在github graphql api上也有体现

workflow配置里面监听milestone相关的事件：
```yml
on:
  issues:
    types: [ milestoned, demilestoned ]
```

您曾经是否尝试过这种方案呢

**Comment by Shell32-Natsu** [comment]
我没有尝试过使用milestone。你担心的高频恶意issue我认为不应该由action的使用者来防御。spam issue对于GitHub的project来说如果真的出现了影响也不仅仅是action，还包括邮件、通知、bot等等都会受影响。这一点我想应该是由GitHub在更上层的位置来防御，现在绝大多数repo都没有出现大量的spam，所以我觉得现在没有必要担心这个问题。
